### PR TITLE
Added continuous single-channel conversion

### PR DESCRIPTION
**Pull request by dzalf**
Dear @CuriousScientist0 

First, thank you for your fantastic work with this library and the hardware project. It's awesome.

Here, I am contributing my _two cents_ with a new serial console input case that enables continuous conversion on a single channel, similar to "Cycle single-ended inputs" enabled by the input character `'C'`. In this case, after sending `'x'` the ADC will continuously print readings from a single channel, as follows: (Channel A0 shown here)

image

This allows for convenient printing of serial data, primarily for testing of single events. Here I am using the [Serial Analyzer](https://github.com/curiores/SerialAnalyzer) App from _curiores_ using decimation for visualization of the changes in a potentiometer (yeah I know that decimating defeats the purpose of having 24 bits of resolution but it's just an example 😉 )

image

This has been tested on an ESP32-S2 WEMOS Mini v1.0, however, I had to use an external USB-UART since I struggled with the native USB port and my serial terminal. 

*Side note:* Based on the issues I described with serial communication, I have been working on additional changes to allow the user to select different serial communication objects (pointer-based) as some boards do not implement easy UART communication, like those that come with an onboard USB-UART converter, like the CP2102N on some ESP32 boards.

### CODE REVIEW

**Comment by CuriousScientist0** [comment]
Hi! I am sorry, but I think I am not going to accept your pull request. There are two things:

1. The function you added **already exists**, see [line 140](https://github.com/CuriousScientist0/ADS1256/blob/4786eef41e78c36301e3f1397f5633e96727af87/examples/ADS1256-Example/ADS1256-Example.ino#L140C6-L140C51     ).  
2. You implemented it using the "wrong" function. Your code uses the function that is based on the ADS1256's RDATA function which is made to read 1 value at a time. My _already existing_ implementation uses the RDATAC function which is specifically made to read a specific channel continuously, according to the selected DRATE value.

**Comment by dzalf** [comment]
Hey, no worries.

My bad! How could I miss that?

I am still experimenting and understanding your implementation.

I will continue working on it and get back to you with more contributions. I still believe that the serial port is one aspect to improve.

Thanks for reviewing it, though.

Closing this.

**Comment by CuriousScientist0** [comment]
Hi! 

No worries! For future reference, please check the documentation I wrote for the library, it explains everything carefully. 

Regarding serial vs. USB, I think that should not be implemented in the library due to the different microcontrollers. What I mean is that some microcontrollers only have UART (ATmega328) while others support native USB (ATmega32U4)...etc. So, they will behave differently. Also, the user might not even want to send the data to the computer but only print it on a display or send it via BT or WiFi (ESP32...etc) to another device or web application. Therefore, I just implemented the library so that each function returns a result but does not directly involve the Serial.print() function. Then it is up to the user what to do with the values. The library is not intended to deal with the transfers. 

Cheers!

**Comment by dzalf** [comment]
Thanks for getting back to me.

I admit that I might have been rushing too much when adding my (rather dumb) block. I was indeed reviewing the manual _while_ writing code.

I just wanted to clarify something regarding the serial ports proposal I mentioned. I did not mean to add this to the library itself but rather to the example code to make testing a bit more flexible. For instance, the ESP32-S2 is notoriously picky when dealing with the native USB port as a serial communications device. On some serial terminals (like YAT) you need to enable Software Control XON/XOFF while on the default terminal from the Arduino IDE, it seems to work just fine.

Upon facing this problem and as a _quick and dirty_ way to avoid this, I plugged my ESP32-S2 into an external USB-UART converter (CP2102N-based) and routed it to UART1. This required me to change all instances of `Serial` with `Serial1` in the example code. This can be a bit cumbersome in case I wanted to revert back to `Serial`

I will present my proposal later in an issues post for your review.

Thanks once again

**Pull request closed without merging**
